---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  namespace: llm
  labels:
    app.kubernetes.io/name: open-webui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-cache
  resources:
    requests:
      storage: 10Gi
