---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: open-webui
  namespace: llm
  labels:
    app.kubernetes.io/name: open-webui
spec:
  type: kv-v2
  vaultAuthRef: default
  mount: mbhome
  path: apps/llm/open-webui
  refreshAfter: 5m
  hmacSecretData: true
  rolloutRestartTargets:
    - kind: Deployment
      name: open-webui
  destination:
    create: true
    name: open-webui
