# Hardware object for MJ11-EC1 node 1.
# Populate mac and ip.address after physical assembly.
# IPMI IP needed to enable rufio BMC management.
---
apiVersion: tinkerbell.org/v1alpha1
kind: Hardware
metadata:
  name: proxmox-node-01
  namespace: tink-system
spec:
  disks:
    - device: /dev/nvme0n1  # M.2 NVMe — Proxmox OS target
  metadata:
    facility:
      facilityCode: homelab
    instance:
      hostname: pve-01
      id: proxmox-node-01
  interfaces:
    - dhcp:
        arch: x86_64
        hostname: pve-01
        ip:
          address: ""       # TODO: static IP to assign to this node
          gateway: 10.20.30.1
          netmask: 255.255.255.0
        lease_time: 86400
        mac: ""             # TODO: MAC address of onboard Intel I210 NIC (port 1)
        name_servers:
          - 10.20.30.1
        uefi: true
      netboot:
        allowPXE: true
        allowWorkflow: true
