General:
  DownloadImages: false
  Interval: 35
  TransitionDuration: 2
  PhotoDateFormat: 'yyyy-MM-dd'  # string
  ImageLocationFormat: 'City,Country'
  ShowClock: true
  ClockFormat: "HH:mm"
  ClockDateFormat: "eee, MMM d"
  ShowProgressBar: true
  ShowPhotoDate: true
  ShowImageDesc: true
  ShowPeopleDesc: true
  ShowTagsDesc: true
  ShowAlbumName: false
  ShowImageLocation: true
  UnitSystem: "metric"
  Language: "en"
  ShowWeatherDescription: false
  WeatherLatLong: "57.769451,12.268760" #Lerum
  WeatherApiKey: "__WEATHER_API_KEY__"
  BaseFontSize: '20px'
  ImageZoom: true
  ImagePan: false
  ImageFill: false
  PlayAudio: false
  Layout: "splitview"
Accounts:
  - ImmichServerUrl: "https://immich.mbhome.biz"
    ApiKeyFile: "/app/secrets/immich-api-key"
    ShowMemories: false
    ShowFavorites: false
    ShowArchived: false
    ShowVideos: true
    # Limit the frame to specific Immich albums by UUID.
    # You can get the UUID from an Immich album URL, for example:
    # https://immich.example.com/albums/85c85b29-c95d-4a8b-90f7-c87da1d518ba
    Albums:
      - "f461c05a-0dd4-484f-bd51-18fcbda860de"
