---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: immichframe
  namespace: immichframe
  labels:
    app.kubernetes.io/name: immichframe
spec:
  type: kv-v2
  mount: mbhome
  path: apps/immichframe
  refreshAfter: 5m
  hmacSecretData: true
  destination:
    create: true
    name: immichframe
