machine:
  install:
    disk: /dev/sda
    wipe: true
  sysctls:
    net.ipv6.conf.all.disable_ipv6: "1"
    net.ipv6.conf.default.disable_ipv6: "1"
  network:
    nameservers:
      - 10.20.30.11
      - 10.20.30.12
      - 10.20.30.1
    interfaces:
      - interface: ens18
        dhcp: true
cluster:
  allowSchedulingOnControlPlanes: false
  # Cilium will be used for CNI, so we need to disable the default Talos CNI.
  network:
    cni:
      name: none
  proxy:
    disabled: true
  apiServer:
    extraArgs:
      oidc-issuer-url: https://dex.apps.mbhome.biz
      oidc-client-id: kubernetes
      oidc-username-claim: email
      oidc-groups-claim: groups
      oidc-username-prefix: "oidc:"
      oidc-groups-prefix: "oidc:"
