machine:
  install:
    disk: /dev/sda
    wipe: true
  sysctls:
    net.ipv6.conf.all.disable_ipv6: "1"
    net.ipv6.conf.default.disable_ipv6: "1"
  network:
    interfaces:
      - interface: eth0
        dhcp: true
cluster:
  allowSchedulingOnControlPlanes: false
  # Cilium will be used for CNI, so we need to disable the default Talos CNI.
  network:
    cni:
      name: none
  proxy:
    disabled: true
