---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: forgejo-postgres-app
  namespace: forgejo
  labels:
    app.kubernetes.io/name: forgejo-postgres
spec:
  type: kv-v2
  vaultAuthRef: default
  mount: mbhome
  path: apps/forgejo/postgres
  refreshAfter: 5m
  hmacSecretData: true
  destination:
    create: true
    name: forgejo-postgres-app
    overwrite: true
