---
forwarders:
  - 1.1.1.1
  - 8.8.8.8

zones:
  - name: mbhome.biz
    records:
      - name: k8s-api
        type: A
        value: 10.20.30.50
        ttl: 300
        state: present

      - name: talos-api
        type: A
        value: 10.20.30.50
        ttl: 300
        state: present

      - name: s3
        type: A
        value: 10.20.30.50
        ttl: 300
        state: present

      - name: s3-api
        type: A
        value: 10.20.30.50
        ttl: 300
        state: present

      - name: proxmox
        type: A
        value: 10.20.30.50
        ttl: 300
        state: present
      
      - name: nas
        type: A
        value: 10.20.30.50
        ttl: 300
        state: present

      - name: mbhome-nas-01-bmc
        type: A
        value: 10.20.30.50
        ttl: 300
        state: present

      - name: mbhome-proxmox-01-bmc
        type: A
        value: 10.20.30.50
        ttl: 300
        state: present

      - name: mbhome-proxmox-02-bmc
        type: A
        value: 10.20.30.50
        ttl: 300
        state: present
      
      - name: mbhome-proxmox-03-bmc
        type: A
        value: 10.20.30.50
        ttl: 300
        state: present
      
      - name: "*.apps"
        type: A
        value: 10.20.30.200 #Cilium internal Gateway
        ttl: 300
        state: present  
