apiVersion: v1alpha1
kind: HostnameConfig
auto: off
hostname: mbhome-talos-cp-02
---
# This block should be filled after the Talos VM is created and assigned a MAC address. The MAC address is used to identify the VM and configure its network interface.
machine:
  network:
    interfaces:
      - deviceSelector:
          hardwareAddr: "02:90:20:30:72:02"
        dhcp: false
        addresses:
          - 10.20.90.72/24
