---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - cloudnative-pg
  - cert-manager
  - nfs-csi
  - gateway-api
  - monitoring
  - metrics-server
  - vault
  - minio
