---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: finance-platform
  namespace: flux-system
  labels:
    app.kubernetes.io/name: finance-platform
    mbhome.biz/source: forgejo
spec:
  interval: 1m
  timeout: 60s
  suspend: false
  url: ssh://git@git.apps.mbhome.biz:2222/denis/finance-platform.git
  ref:
    branch: main
  secretRef:
    name: finance-platform-deploy-key
