---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - vaultauth.yaml
  - vaultstaticsecret-open-webui-client.yaml
  - vaultstaticsecret-forgejo-client.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - httproute.yaml
  - ciliumnetworkpolicy.yaml
  - rbac.yaml
