---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: open-webui-client
  namespace: dex
  labels:
    app.kubernetes.io/name: dex
spec:
  type: kv-v2
  vaultAuthRef: default
  mount: mbhome
  path: apps/dex/open-webui
  refreshAfter: 5m
  hmacSecretData: true
  rolloutRestartTargets:
    - kind: Deployment
      name: dex
  destination:
    create: true
    name: dex-open-webui-client
