---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: forgejo
  namespace: forgejo
  labels:
    app.kubernetes.io/name: forgejo
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: forgejo
