---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: forgejo-config
  namespace: forgejo
  labels:
    app.kubernetes.io/name: forgejo
spec:
  type: kv-v2
  vaultAuthRef: default
  mount: mbhome
  path: apps/forgejo/config
  refreshAfter: 5m
  hmacSecretData: true
  rolloutRestartTargets:
    - kind: Deployment
      name: forgejo
  destination:
    create: true
    name: forgejo-config
    overwrite: true
