---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-runner-config
  namespace: forgejo-runner
  labels:
    app.kubernetes.io/name: forgejo-runner
data:
  config.yaml: |
    log:
      level: info

    runner:
      capacity: 1
      envs:
        DOCKER_HOST: unix:///var/run/docker.sock
      env_file: ""
      timeout: 3h
      insecure: false
      fetch_timeout: 5s
      fetch_interval: 2s
      labels:
        - docker:docker://ghcr.io/catthehacker/ubuntu:act-22.04
        - ubuntu-latest:docker://ghcr.io/catthehacker/ubuntu:act-22.04
        - self-hosted:docker://ghcr.io/catthehacker/ubuntu:act-22.04

    cache:
      enabled: true
      dir: /data/cache
      host: ""
      port: 0

    container:
      network: ""
      enable_ipv6: false
      privileged: false
      options: ""
      workdir_parent: /workspace
      valid_volumes: []
      docker_host: unix:///var/run/docker/docker.sock
      force_pull: true
      force_rebuild: false

    host:
      workdir_parent: /data/host-work
