---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: forgejo-runner
  namespace: forgejo-runner
  labels:
    app.kubernetes.io/name: forgejo-runner
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: forgejo-runner
