---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-runner-data
  namespace: forgejo-runner
  labels:
    app.kubernetes.io/name: forgejo-runner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-cache
  resources:
    requests:
      storage: 2Gi
