---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sync
  namespace: forgejo-runner
  labels:
    app.kubernetes.io/name: forgejo-runner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: forgejo-runner
  namespace: forgejo-runner
  labels:
    app.kubernetes.io/name: forgejo-runner
automountServiceAccountToken: false
