---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: default
  namespace: forgejo-runner
  labels:
    app.kubernetes.io/name: forgejo-runner
spec:
  vaultConnectionRef: vault-secrets-operator/default
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: app-forgejo-runner
    serviceAccount: vault-sync
    audiences:
      - vault
