---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: forgejo-runner-registration
  namespace: forgejo-runner
  labels:
    app.kubernetes.io/name: forgejo-runner
spec:
  type: kv-v2
  vaultAuthRef: default
  mount: mbhome
  path: apps/forgejo-runner/registration
  refreshAfter: 5m
  hmacSecretData: true
  rolloutRestartTargets:
    - kind: Deployment
      name: forgejo-runner
  destination:
    create: true
    name: forgejo-runner-registration
