---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - vaultauth.yaml
  - vaultstaticsecret-pushover.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - httproutes.yaml
  - ciliumnetworkpolicy.yaml
  - pvc-dashboard.yaml
  - pvc-rules.yaml
