---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: alertmanager-pushover
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
spec:
  type: kv-v2
  vaultAuthRef: default
  mount: mbhome
  path: apps/monitoring/pushover
  refreshAfter: 5m
  hmacSecretData: true
  destination:
    create: true
    name: alertmanager-pushover
