---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudflared
  namespace: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
