---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: immich-album-sync
  namespace: flux-system
  labels:
    app.kubernetes.io/name: immich-album-sync
    mbhome.biz/source: forgejo
spec:
  interval: 1m
  timeout: 60s
  suspend: false
  url: ssh://git@git.apps.mbhome.biz:2222/denis/immich-album-sync.git
  ref:
    branch: main
  secretRef:
    name: immich-album-sync-deploy-key
