---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: immich-album-sync
  namespace: immich-album-sync
  labels:
    app.kubernetes.io/name: immich-album-sync
spec:
  type: kv-v2
  vaultAuthRef: default
  mount: mbhome
  path: apps/immich-album-sync
  refreshAfter: 5m
  hmacSecretData: true
  destination:
    create: true
    name: immich-album-sync
