---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: whoami
  namespace: whoami
  labels:
    app.kubernetes.io/name: whoami
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami
